name: worship_hymn
description: "A new Flutter project."
version: 1.0.0+5

environment:
  sdk: ^3.5.4

dependencies:
  flutter_svg: ^2.2.1
  flutter:
    sdk: flutter
  kakao_flutter_sdk_user: ^1.9.7
  http: ^1.5.0
  photo_view: ^0.15.0
  intl: ^0.20.2
  url_launcher: ^6.3.0

  flutter_naver_login: ^2.1.1

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1

  google_sign_in: ^7.1.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4



dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"   # 아이콘 경로

  flutter_test:
    sdk: Flutter

  flutter_lints: ^4.0.0
  
flutter:
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard_black.otf
        - asset: assets/fonts/pretendard_regular.otf
        - asset: assets/fonts/pretendard_bold.otf
        - asset: assets/fonts/pretendard_extrabold.otf
        - asset: assets/fonts/pretendard_extralight.otf
        - asset: assets/fonts/pretendard_light.otf
        - asset: assets/fonts/pretendard_medium.otf
        - asset: assets/fonts/pretendard_semibold.otf
        - asset: assets/fonts/pretendard_thin.otf
          weight: 700
  assets:
    - assets/icon/app_icon.png
    - assets/icon/kakao.png
    - assets/icon/naver.png
    - assets/icon/google.png
    - assets/image/login_screen.png
    - assets/icon/home.svg
    - assets/icon/score.svg
    - assets/icon/bookmark.svg
    - assets/icon/setting.svg
    - assets/icon/music.svg
    - assets/scores/

  uses-material-design: true
